### ISSUE TITLE
URL not correctly replaced

### ISSUE THREAD

**Issue by davidbrazilparker** [sjmulder/urlrewrite-chrome#1]
I tried to replace http://facebook.com with https://www.facebook.com/?sk=h_chr in order to manipulate the Facebook JQuery to show my recent feed instead of my 'top' feed. However this resulted in the script just FLOODING the url with /?sk=h_chr/?sk=h_chr/?sk=h_chr. I believe there is just an issue with some looping in your code. I'll look at it tomorrow and see what might be the issue.

**Comment by sjmulder** [comment]
Thanks! I'll also take a look if I get around to it.

**Comment by sjmulder** [comment]
Hi,

Obviously I haven't gotten around to it. I'm sorry to have kept you waiting. However, I haven't really been maintaining this project and have since moved on to other things so I'm going to archive this project.

Of course, anyone is free to fork and build on this project, that's the beauty of free software.

Cheers,
Sijmen
